services:
  - type: web
    name: chazefashion
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ChazeFashion.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ChazeFashion.settings
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: DEBUG
        value: False
